// Mock data — realistic professional contacts and campaigns
// Replace by importing from API when backend is connected.
// Keep this file isolated: only contact-service.ts and campaign-service.ts import from here.

import type { Campaign, OutreachContact } from '@/types/outreach'

export const MOCK_CONTACTS: OutreachContact[] = [
  {
    id: 'c1',
    firstName: 'Rajesh',
    lastName: 'Sharma',
    email: 'rajesh@abctechnologies.com',
    jobTitle: 'Founder',
    companyName: 'ABC Technologies',
    companyDomain: 'abctechnologies.com',
    location: 'Delhi, India',
    industry: 'Technology',
    linkedinUrl: 'https://linkedin.com',
    verified: 'verified',
  },
  {
    id: 'c2',
    firstName: 'Aman',
    lastName: 'Gupta',
    email: 'aman@xyzlabs.in',
    jobTitle: 'Co-Founder',
    companyName: 'XYZ Labs',
    companyDomain: 'xyzlabs.in',
    location: 'Bangalore, India',
    industry: 'SaaS',
    verified: 'verified',
  },
  {
    id: 'c3',
    firstName: 'Priya',
    lastName: 'Singh',
    email: 'priya.singh@novalabs.io',
    jobTitle: 'HR Manager',
    companyName: 'Nova Labs',
    companyDomain: 'novalabs.io',
    location: 'Mumbai, India',
    industry: 'Technology',
    verified: 'likely',
  },
  {
    id: 'c4',
    firstName: 'Rahul',
    lastName: 'Verma',
    email: 'rahul.verma@acmecorp.com',
    jobTitle: 'Recruiter',
    companyName: 'Acme Corp',
    companyDomain: 'acmecorp.com',
    location: 'Pune, India',
    industry: 'Consulting',
    verified: 'verified',
  },
  {
    id: 'c5',
    firstName: 'Neha',
    lastName: 'Kapoor',
    email: 'neha@techbridge.io',
    jobTitle: 'Talent Acquisition Lead',
    companyName: 'TechBridge',
    companyDomain: 'techbridge.io',
    location: 'Hyderabad, India',
    industry: 'Recruitment',
    verified: 'likely',
  },
  {
    id: 'c6',
    firstName: 'Arjun',
    lastName: 'Mehta',
    email: 'arjun.mehta@nexusai.com',
    jobTitle: 'CEO',
    companyName: 'Nexus AI',
    companyDomain: 'nexusai.com',
    location: 'San Francisco, CA',
    industry: 'Artificial Intelligence',
    linkedinUrl: 'https://linkedin.com',
    verified: 'verified',
  },
  {
    id: 'c7',
    firstName: 'Shreya',
    lastName: 'Nair',
    email: 'shreya@clarityhq.com',
    jobTitle: 'Engineering Manager',
    companyName: 'Clarity HQ',
    companyDomain: 'clarityhq.com',
    location: 'Remote',
    industry: 'Product',
    verified: 'likely',
  },
  {
    id: 'c8',
    firstName: 'Vikram',
    lastName: 'Bose',
    email: 'vikram.bose@scalefront.com',
    jobTitle: 'Hiring Manager',
    companyName: 'Scalefront',
    companyDomain: 'scalefront.com',
    location: 'Gurgaon, India',
    industry: 'Fintech',
    verified: 'unknown',
  },
  {
    id: 'c9',
    firstName: 'Divya',
    lastName: 'Reddy',
    email: 'divya@kineticworks.io',
    jobTitle: 'Talent Partner',
    companyName: 'Kinetic Works',
    companyDomain: 'kineticworks.io',
    location: 'Chennai, India',
    industry: 'Design',
    verified: 'verified',
  },
  {
    id: 'c10',
    firstName: 'Siddharth',
    lastName: 'Joshi',
    email: 'siddharth@looptech.dev',
    jobTitle: 'Co-Founder & CTO',
    companyName: 'Loop Tech',
    companyDomain: 'looptech.dev',
    location: 'Bangalore, India',
    industry: 'Developer Tools',
    linkedinUrl: 'https://linkedin.com',
    verified: 'verified',
  },
  {
    id: 'c11',
    firstName: 'Kavya',
    lastName: 'Iyer',
    email: 'kavya.iyer@brightpath.com',
    jobTitle: 'HR Business Partner',
    companyName: 'Bright Path',
    companyDomain: 'brightpath.com',
    location: 'Coimbatore, India',
    industry: 'Education',
    verified: 'likely',
  },
  {
    id: 'c12',
    firstName: 'Rishi',
    lastName: 'Tandon',
    email: 'rishi@stackbase.io',
    jobTitle: 'Founder',
    companyName: 'Stackbase',
    companyDomain: 'stackbase.io',
    location: 'London, United Kingdom',
    industry: 'Infrastructure',
    verified: 'verified',
  },
]

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp1',
    name: 'Founder Outreach',
    createdAt: '2026-08-14T10:00:00Z',
    subject: 'Quick introduction — {{firstName}}',
    body: 'Hello {{firstName}},\n\nI came across {{companyName}} and was really impressed by what you\'re building.\n\nBest,\nAnshu',
    recipients: 10,
    delivered: 9,
    bounced: 1,
    replies: 2,
    status: 'active',
    contacts: [
      { id: 'cc1', contact: MOCK_CONTACTS[0]!, status: 'delivered', personalizedSubject: 'Quick introduction — Rajesh', personalizedBody: '', sentAt: '2026-08-14T11:00:00Z' },
      { id: 'cc2', contact: MOCK_CONTACTS[1]!, status: 'delivered', personalizedSubject: 'Quick introduction — Aman', personalizedBody: '', sentAt: '2026-08-14T11:01:00Z' },
      { id: 'cc3', contact: MOCK_CONTACTS[2]!, status: 'replied', personalizedSubject: 'Quick introduction — Priya', personalizedBody: '', sentAt: '2026-08-14T11:02:00Z', repliedAt: '2026-08-14T12:00:00Z' },
      { id: 'cc4', contact: MOCK_CONTACTS[3]!, status: 'bounced', personalizedSubject: 'Quick introduction — Rahul', personalizedBody: '', sentAt: '2026-08-14T11:03:00Z' },
      { id: 'cc5', contact: MOCK_CONTACTS[4]!, status: 'opened', personalizedSubject: 'Quick introduction — Neha', personalizedBody: '', sentAt: '2026-08-14T11:04:00Z', openedAt: '2026-08-14T14:00:00Z' },
    ],
  },
  {
    id: 'camp2',
    name: 'HR Outreach — August',
    createdAt: '2026-08-10T08:00:00Z',
    subject: 'Connecting with the team at {{companyName}}',
    body: 'Hi {{firstName}},\n\nI\'d love to connect about opportunities at {{companyName}}.\n\nBest regards,\nAnshu',
    recipients: 25,
    delivered: 24,
    bounced: 1,
    replies: 5,
    status: 'completed',
    contacts: [],
  },
  {
    id: 'camp3',
    name: 'Startup Batch — Series A',
    createdAt: '2026-08-02T09:00:00Z',
    subject: 'Admiring {{companyName}}\'s growth',
    body: 'Hello {{firstName}},\n\nI\'ve been following {{companyName}}\'s journey.\n\nBest,\nAnshu',
    recipients: 50,
    delivered: 47,
    bounced: 3,
    replies: 8,
    status: 'completed',
    contacts: [],
  },
]
